/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app/**/*.{js,vue,ts}",
    "./app.vue",
    "./error.vue",
  ],
  theme: {
    extend: {
      colors: {
        // ─── TEXT ────────────────────────────────────────────────
        text: {
          dark: {
            primary: "#101828",
            secondary: "#717680",
            tertiary: "#d5d7da",
          },
          light: {
            primary: "#ffffff",
            secondary: "#f5f5f5",
          },
          disabled: "#a4a7ae",
          primary: "#141b4d",
          secondary: "#324cf9",
          danger: "#a0112b",
          success: "#167a17",
          info: "#045691",
          warning: "#bcb005",
        },

        // ─── ICON ─────────────────────────────────────────────────
        icon: {
          dark: {
            primary: "#101828",
            secondary: "#717680",
            tertiary: "#d5d7da",
          },
          light: {
            primary: "#ffffff",
            secondary: "#f5f5f5",
          },
          disabled: "#a4a7ae",
          primary: "#141b4d",
          secondary: "#324cf9",
          "secondary-pressed": "#2234b1",
          danger: "#890c2f",
          "danger-pressed": "#5c052e",
          success: "#106818",
          "success-pressed": "#074618",
          info: "#02427c",
          "info-pressed": "#012354",
          warning: "#bcb005",
          "warning-pressed": "#877c02",
          loading: "#d5d7da",
        },

        // ─── BACKGROUND ───────────────────────────────────────────
        bg: {
          light: "#fdfbf2",
          dark: "#030b10",
          "surface-neutral-light": "#fafafa",
          "surface-neutral-dark": "#515252",
          "surface-primary": "#eaf5ff",
          "surface-secondary": "#edf1ff",
          "surface-danger": "#fdf6f8",
          "surface-success": "#f1fcdb",
          "surface-info": "#f0f5f2",
          "surface-warning": "#fdf6e5",
          "fill-primary": "#141B4D",
          "fill-secondary": "#324cf9",
          "fill-danger": "#990c21",
          "fill-success": "#108b18",
          "fill-info": "#045691",
          "fill-warning": "#bcb005",
          "button-effect": "#030b100d",
          "button-primary-default": "#141b4d",
          "button-primary-hover": "#222d81",
          "button-primary-pressed": "#324cf9",
          "button-secondary-default": "#324cf9",
          "button-secondary-hover": "#f6faff",
          "button-secondary-pressed": "#c5daf7",
          "button-danger-default": "#990c21",
          "button-danger-hover": "#dc4154",
          "button-danger-pressed": "#f5a5b2",
          "button-success-default": "#108b18",
          "button-success-hover": "#4ba143",
          "button-success-pressed": "#8daf52",
          "button-info-default": "#045691",
          "button-info-hover": "#5c5c5e",
          "button-info-pressed": "#0d2f50",
          "button-warning-default": "#bcb005",
          "button-warning-hover": "#eae381",
          "button-warning-pressed": "#f1f5c6",
          "button-contained-disabled": "#ede7ae",
          "button-outlined-default": "#f6fafe",
          "button-outlined-hover": "rgba(3,11,16,0.48)",
          "button-outlined-pressed": "rgba(3,55,47,0.12)",
          "table-header": "rgba(241,242,245,0.73)",
          "form-default": "#f5f5f1",
        },

        // ─── BORDER ───────────────────────────────────────────────
        border: {
          "neutral-light": "rgba(240,240,240,0.10)",
          "neutral-dark": "rgba(48,49,49,0.13)",
          dark: "#030b10",
          "surface-primary": "#e4f5ff",
          "surface-secondary": "#eac2ff",
          "surface-danger": "#ffd6d6",
          "surface-success": "#cbf9cb",
          "surface-info": "#c4f0f9",
          "surface-warning": "#fbf3ca",
          "fill-primary": "#141b4d",
          "fill-secondary": "#324cf9",
          "fill-danger": "#990c2f",
          "fill-success": "#167a47",
          "fill-info": "#044881",
          "fill-warning": "#bcb005",
          "form-focused": "#252b57",
          "form-askstoffload": "rgba(3,3,18,0.15)",
          "form-table": "rgba(3,5,13,0.79)",
          "form-default": "#9ebadb",
          "form-danger": "#ea0712",
          "form-warning": "#bcb005",
          "form-success": "#167a17",
          "form-info": "#045491",
        },
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [
    function ({ addBase }) {
      addBase({
        "*": { fontFamily: "'Hanken Grotesk', sans-serif" },
      });
    },
  ],
};
